### ISSUE TITLE
deepmusic lib

### ISSUE THREAD

**Issue by soltanireza** [Conchylicultor/MusicGenerator#12]
hi
how can i actually install deepmusic itself?
i can not import dependencies of deepmusic...

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-9392e14f5b37> in <module>()
----> 1 from deepmusic.moduleloader import ModuleLoader
      2 from deepmusic.keyboardcell import KeyboardCell
      3 import deepmusic.songstruct as music
      4 import numpy as np
      5 import tensorflow

ModuleNotFoundError: No module named 'deepmusic'

**Comment by ShadabFaiz** [comment]
is it resolved? I'm also getting same error

**Comment by mounikagajja** [comment]
Hi
Is it resolved?

**Comment by IceStarDragon707** [comment]
@ShadabFaiz 
> is it resolved? I'm also getting the same error

==> use git clone to download the repository

@mounikagajja 
> Hi Is it resolved?

==> use git clone to download the repository

however, the code inside using the battered code of tensorflow at current version
