### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by Eumi** [Conchylicultor/MusicGenerator#5]
File "C:\musicai\deepmusic\composer.py", line 255, in _main_train
    next_batch_test = batches_test[self.glob_step % len(batches_test)]  # Generate test batches in a cycling way (test set smaller than train set)
ZeroDivisionError: integer division or modulo by zero

i allways get this =,O pls help (win 10 64bit)

**Comment by Conchylicultor** [comment]
The error seems quite explicit: len(batches_test) == 0. It's probably because you don't have any training songs.

**Comment by Eumi** [comment]
how can i fix that?

**Comment by Conchylicultor** [comment]
By putting some midi songs inside the `data/midi/` folder. But the current version mainly generates garbage songs so I'm not sure that it worth it.

**Comment by Eumi** [comment]
hmm i have the midi files in it =/ ...i dont understand ...i play a bit arround ...ty others ... hmm really? only carbage? =,O i was so looking forward to it

**Comment by Eumi** [comment]
thanks btw

**Comment by Eumi** [comment]
omg it works now =,,,,,O thanks so much =D your my hero! i tried so hard for so long..but i dont know anything bout programming ....THANKS!! =D  (it allways loaded some file before it fails...i deleted it and it read the midis again and so now it works! )

**Comment by Conchylicultor** [comment]
Great :) The program pre-process the data only the first time the program is launched and then reuse those pre-porcessed data. It's possible that there was no data the first time the program was loaded and so it reloaded an incorrect dataset every time.

**Comment by tanmay2211** [comment]
hey @Eumi @Conchylicultor how did you solve this? i already have midi files inside data/midi
